### PR TITLE
#5 Custom message being honored as specified by the options block in …

### PR DESCRIPTION
**Pull request by vraravam**
…the model.

### CODE REVIEW

**Comment by PareshGupta** [comment]
@vraravam - Thanks for the Pull Request.
We are already using `options[:message]` key for showing errors on invalid child object. Hence this will override that functionality. 

cc: @akshay-vishnoi

**Comment by vraravam** [comment]
@PareshGupta - so, did you want me to use another key? If that is all that you want, i can change it.

**Comment by PareshGupta** [comment]
@vraravam - Yes.

cc: @akshay-vishnoi

**Comment by akshay-vishnoi** [comment]
@jitendra - We were already using options[:message] key for showing errors on invalid child object. 
Shouldn't we change the key for the error?

**Comment by jitendra** [comment]
@akshay-vishnoi, @PareshGupta and @vraravam I think the purpose of the PR was to add the invalid child error message on parent level for easy access.

I understand that library could have ability to allow different message for the parent as well but in my opinion that would be a separate issue/enhancement. Please let me know if we are not on the same page.

**Pull request merged**
